version: "3.8"

services:
  backend:
    build: ./backend
    container_name: meu-brasilapi-backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app
    command: ["node", "server.js"]
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    container_name: meu-brasilapi-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  sqlite_data:
